{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..|5..\"}[1m])) / sum(rate(http_server_requests_seconds_count[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[1h])) by (uri))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_server_requests_seconds_count[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "service": "jaeger-all-in-one" }
   ]
  },
  {
   "title": "Last traces",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "limit": 20, "service": "jaeger-all-in-one" }
   ]
  }
 ]
}